language: scala
jdk:
  - oraclejdk8
sudo: required
dist: trusty
scala:
  - 2.10.5
  - 2.11.7

cache:
  directories:
  - $HOME/.ivy2/cache


script:
  - "sbt ++$TRAVIS_SCALA_VERSION -Dtravis=true test"
  - "sbt ++$TRAVIS_SCALA_VERSION -Dtravis=true it:test"
  - "sbt ++$TRAVIS_SCALA_VERSION -Dtravis=true assembly"
